"""Recreate tables

Revision ID: 2a26c5bfa0e2
Revises: 
Create Date: 2025-06-04 09:07:42.906583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a26c5bfa0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('proteines', sa.Float(), nullable=True),
    sa.Column('glucides', sa.Float(), nullable=True),
    sa.Column('lipides', sa.Float(), nullable=True),
    sa.Column('type_aliment', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('buffets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evenement', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('lieu', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aliment_allergie',
    sa.Column('aliment_id', sa.Integer(), nullable=False),
    sa.Column('allergie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aliment_id'], ['aliments.id'], ),
    sa.ForeignKeyConstraint(['allergie_id'], ['allergies.id'], ),
    sa.PrimaryKeyConstraint('aliment_id', 'allergie_id')
    )
    op.create_table('buffet_recette',
    sa.Column('buffet_id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buffet_id'], ['buffets.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('buffet_id', 'recette_id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=150), nullable=False),
    sa.Column('chemin', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.String(length=20), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recette_aliment',
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('aliment_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aliment_id'], ['aliments.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('recette_id', 'aliment_id')
    )
    op.create_table('recommandations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('type_regime', sa.String(length=100), nullable=True),
    sa.Column('aliments_recommandes', sa.Text(), nullable=True),
    sa.Column('aliments_interdits', sa.Text(), nullable=True),
    sa.Column('allergenes', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommandations')
    op.drop_table('recette_aliment')
    op.drop_table('menus')
    op.drop_table('images')
    op.drop_table('buffet_recette')
    op.drop_table('aliment_allergie')
    op.drop_table('utilisateurs')
    op.drop_table('recettes')
    op.drop_table('categories')
    op.drop_table('buffets')
    op.drop_table('allergies')
    op.drop_table('aliments')
    # ### end Alembic commands ###
